
# Adds namespace to all resources.
namespace: fleet-system

resources:
- ./component_namespace.yaml
- ./service_account.yaml
- ./clusterrole_binding.yaml
- ./deployment.yaml

images:
- name: work-api-controller:latest
  newName: nerdyyatrice/work-api-controller
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
